// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aimzeter/wuts/three (interfaces: StudentStore)

// Package mocks is a generated GoMock package.
package mocks

import (
	three "github.com/aimzeter/wuts/three"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStudentStore is a mock of StudentStore interface
type MockStudentStore struct {
	ctrl     *gomock.Controller
	recorder *MockStudentStoreMockRecorder
}

// MockStudentStoreMockRecorder is the mock recorder for MockStudentStore
type MockStudentStoreMockRecorder struct {
	mock *MockStudentStore
}

// NewMockStudentStore creates a new mock instance
func NewMockStudentStore(ctrl *gomock.Controller) *MockStudentStore {
	mock := &MockStudentStore{ctrl: ctrl}
	mock.recorder = &MockStudentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStudentStore) EXPECT() *MockStudentStoreMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockStudentStore) Create(arg0 three.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockStudentStoreMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentStore)(nil).Create), arg0)
}
